version: "3.5"

services:
  docker-stats:
    image: marktermaat/docker-stats-influxdb:latest
    environment:
      - LOG_LEVEL=INFO
      - INFLUXDB_HOST=192.168.2.4
      - INFLUXDB_DATABASE=docker-stats
    volumes:
      - ./log:/var/log
      - /var/run/docker.sock:/var/run/docker.sock
